import React from 'react';
import Link from 'next/link';
import Image from 'next/image';

export const metadata = {
  title: "D2C & Web Design Case Studies | Results — raushang4 E-Commerce",
  description: "Selected raushang4 E-Commerce case studies with commercial context, implementation detail, and measurable outcomes across D2C ecommerce, Shopify stores, and lead generation.",
};

export default function CaseStudyPage() {
  return (
    <>
      <section className="page-hero-wrap"> <div className="page-hero"> <div className="eyebrow-pill">Case Studies</div> <h1> Detailed work with <em> context and outcomes.</em></h1> <p> This archive is for the full raushang4 E-Commerce case studies only — the work where we can show the problem, the thinking, and the result clearly.</p> </div> </section> <div className="filter-bar-wrap"> <div className="filter-bar"> <span className="filter-label">Filter:</span> <button className="filter-btn active" data-filter="all"> All </button><button className="filter-btn" data-filter="d2c"> D2C & Ecommerce </button><button className="filter-btn" data-filter="web"> Web Design </button> </div> </div> <section className="portfolio-section"> <div className="portfolio-grid" id="portfolio-grid"> <div className="cs-card-wrap" data-category="web"> <Link href="/case-study/dream-spark-events" className="case-card"> <div className="case-img case-img--photo"> <Image src="https://cdn.sanity.io/images/zcj1brqz/production/42e3c04f2308665e065473b28a7a9ea708a8dc3b-2752x1536.png?w=900&auto=format&fit=max&q=75" alt="Dream Spark Events" width={900} height={600} /> <span className="case-img-label">WooCommerce Development</span> </div> <div className="case-body"> <div className="case-meta"> <span className="case-tag">Service Marketplace · Events & Venue Booking</span> <span className="case-metric-chip">Custom Built - 100%</span> </div> <h3 className="case-title">Dream Spark Events — Multi-Vendor Event & Venue Booking Platform</h3> <p className="case-desc">A complete multi-vendor event marketplace built from scratch —
artist registration, venue listings, date-based booking workflows, and
a structured service catalog, all within a single WooCommerce platform.</p> <div className="case-outcomes"> <span className="case-outcome"> <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><polyline points="18 15 12 9 6 15"></polyline></svg> 100% Custom Built </span><span className="case-outcome"> <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><polyline points="18 15 12 9 6 15"></polyline></svg> 40+ Custom Fields Implemented </span> </div> </div> </Link> </div><div className="cs-card-wrap" data-category="d2c"> <Link href="/case-study/mopadz" className="case-card"> <div className="case-img case-img--photo"> <Image src="https://cdn.sanity.io/images/zcj1brqz/production/bff1bb5dcfc542312ec5651b1ef0580b83704df9-2752x1536.png?w=900&auto=format&fit=max&q=75" alt="Mopadz" width={900} height={600} /> <span className="case-img-label">Shopify Development</span> </div> <div className="case-body"> <div className="case-meta"> <span className="case-tag">D2C · Premium Desk Mats</span> <span className="case-metric-chip">Conversion Architecture - 100%</span> </div> <h3 className="case-title">Mopadz — Premium D2C Shopify Store Built From Scratch</h3> <p className="case-desc">A premium Shopify storefront built from zero — custom UI/UX,
structured product pages, and a conversion-focused layout designed
to support customer acquisition from day one.</p> <div className="case-outcomes"> <span className="case-outcome"> <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><polyline points="18 15 12 9 6 15"></polyline></svg> 100% Built From Scratch </span><span className="case-outcome"> <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><polyline points="18 15 12 9 6 15"></polyline></svg> Day One Launch Fully Operational </span> </div> </div> </Link> </div><div className="cs-card-wrap" data-category="d2c"> <Link href="/case-study/red-sirocco" className="case-card"> <div className="case-img case-img--photo"> <Image src="https://cdn.sanity.io/images/zcj1brqz/production/da53e10d416868c2d046d3b4833a6ee2856042bc-2752x1536.png?w=900&auto=format&fit=max&q=75" alt="Red Sirocco" width={900} height={600} /> <span className="case-img-label">WooCommerce Development</span> </div> <div className="case-body"> <div className="case-meta"> <span className="case-tag">D2C · Coffee</span> <span className="case-metric-chip">Mobile Usability Score - +65%</span> </div> <h3 className="case-title">Red Sirroco — Conversion-Ready WooCommerce Store Redesign</h3> <p className="case-desc">A basic WooCommerce store rebuilt with structured product pages,
conversion-focused UI, and a mobile-first layout — taken from redesign
to full live deployment.</p> <div className="case-outcomes"> <span className="case-outcome"> <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><polyline points="18 15 12 9 6 15"></polyline></svg> 100% Store Rebuilt & Live </span><span className="case-outcome"> <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><polyline points="18 15 12 9 6 15"></polyline></svg> 3x Product Page Structure Improved </span> </div> </div> </Link> </div><div className="cs-card-wrap" data-category="web"> <Link href="/case-study/kaapi-machines" className="case-card"> <div className="case-img case-img--photo"> <Image src="https://cdn.sanity.io/images/zcj1brqz/production/2240fcfb18ebad328f1e8520824a026bdbf5212b-2752x1536.png?w=900&auto=format&fit=max&q=75" alt="Kaapi Machines" width={900} height={600} /> <span className="case-img-label">WooCommerce Development</span> </div> <div className="case-body"> <div className="case-meta"> <span className="case-tag">B2B · Coffee Machines & Equipment</span> <span className="case-metric-chip">Product Archive Browsing Experience - 3x Cleaner</span> </div> <h3 className="case-title">Kaapi Machines — B2B Store & Catalog Experience Redesign</h3> <p className="case-desc">A large B2B equipment catalog redesigned for clarity — AJAX-powered
filtering, structured product pages, and a scalable content layout built
without touching existing SEO performance.</p> <div className="case-outcomes"> <span className="case-outcome"> <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><polyline points="18 15 12 9 6 15"></polyline></svg> 3x Cleaner Product Archive Browsing Experience </span><span className="case-outcome"> <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><polyline points="18 15 12 9 6 15"></polyline></svg> AJAX Filtering Implemented Across Products & Events </span> </div> </div> </Link> </div> </div> </section> <section className="cta-section"> <div className="cta-inner"> <h2> Think your project belongs here?</h2> <p> Tell us what you're working on and we'll tell you honestly if we can help.</p> <Link href="/contact" className="btn-cta">Start a conversation →</Link> </div> </section> 
    </>
  );
}
